---
 - name: Add Elasticsearch apt key.
   apt_key:
     url: https://packages.elastic.co/GPG-KEY-elasticsearch
     state: present
 
 - name: Add ElasticStack repo
   apt_repository:
     repo: 'deb https://artifacts.elastic.co/packages/{{ elastic_repo_version }}/apt stable main'
     state: present
     update_cache: yes
